models:
  - name: movies
    description: Dimension table for cleansed movie metadata
    columns:
      - name: movie_id
        description: Primary key of the movie
        tests:
          - not_null
      - name: movie_title
        description: Standardized movie title
        tests:
          - not_null
      - name: genre_array
        description: List of genres in array format
      - name: genres
        description: Raw genre string from source

  - name: users
    description: Dimension table of unique users from both ratings and tags
    columns:
      - name: user_id
        description: Unique user identifier
        tests:
          - not_null

  - name: ratings
    description: Fact table of user ratings for movies
    columns:
      - name: user_id
        description: Foreign key to dim_users
        tests:
          - not_null
      - name: movie_id
        description: Foreign key to dim_movies
        tests:
          - not_null
          - relationships:
              to: ref('dim_movies')
              field: movie_id
      - name: rating
        description: User's rating for a movie
        tests:
          - not_null
      - name: rating_timestamp
        description: Unix timestamp when the rating was made
