version: 2 

sources:
  - name: netflix
    schema: raw 
    tables:
      - name: r_movies
        identifier: raw_movies 
      - name: r_ratings
        identifier: raw_ratings 
      - name: r_tags 
        identifier: raw_tags 
      - name: r_genome_tags 
        identifier: raw_genome_tags 
      - name: r_genome_scores 
        identifier: raw_genome_scores 
      - name: r_links 
        identifier: raw_links 

        